server:
  port: 8080
spring:
  application:
    name: pluto-sys-web
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pluto?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
      driver-class-name:
      #连接池
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

